FROM ubuntu:22.04 AS builder

RUN apt-get update && apt-get install -y \
    g++ \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY server.cpp ./

RUN g++ server.cpp -o server_node -O3 -pthread -lcrypto

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/server_node .

ENTRYPOINT ["./server_node"]