version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: cpp-server
    ports:
      - "8080:8080"

  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: cpp-client
    depends_on:
      - server
    volumes:
      - ./hashrate.txt:/app/hashrate.txt
    command: ["server", "8080", "/app/hashrate.txt"]